# Generated by Django 5.0.6 on 2024-08-05 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_remove_order_delivery_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivery_datetime",
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
